<?php
/**
 * Apache Solr Search Engine for Magento
 *
 * @category  DMC
 * @package   DMC_Solr
 * @author    Team Magento <magento@digitalmanufaktur.com>
 * @version   0.1.6
 */
?>
<?php if ($additionalDocs = $this->getAdditionalDocs()):?> 
	<?php foreach ($additionalDocs as $key => $item):?>
	   <?php
	       $class = "";
	       if($this->getRequest()->getParam('type')==$key)
           {
                $class = "class=\"active\"";
           }
	   ?>
		<li class="tab"><a <?php echo $class; ?> href="<?php echo Mage::getBaseURL(); ?>solr/additional/?q=<?php echo $this->term; ?>&type=<?php echo $key; ?>"><?php echo $this->__($this->mapping[$key]) ?></a></li>
    <?php endforeach;?>
<?php endif; ?>